# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

arr = np.random.uniform(0, 20, (4, 7))
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())

print(arr)
print(' ')
print(normalized_arr)

[[ 6.26305526 10.84143584 13.19475978 18.93684549 18.65076439  0.11539564
  13.7464468 ]
 [17.44449453 15.51759372 17.65517374 14.74377823  1.03337353  7.43576909
  10.93750983]
 [10.45554536  7.44542978 17.30446943  7.77602084 17.85833418 14.26982006
  11.42612368]
 [11.58603808  2.00764862  3.62731765  0.30748573 16.6739211  17.19394157
  11.31189471]]
 
[[0.3266305  0.56988384 0.69491799 1.         0.98480026 0.
  0.7242296 ]
 [0.9207101  0.81833218 0.93190367 0.77721869 0.04877296 0.38893781
  0.57498834]
 [0.54938115 0.38945109 0.91327044 0.40701568 0.94269776 0.75203688
  0.60094882]
 [0.60944521 0.10053705 0.18659147 0.01020591 0.87976886 0.907398
  0.59487973]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr1 = np.random.randint(0, 10, (8, 10))
print(arr1)

mini=1000
ind=0
a=[sum(i) for i in arr1]

for j in range(len(a)):
  if a[j]<mini:
    mini = a[j]
    ind = j

print('строка:', arr1[ind])
print('сумма:', mini, 'индекс строки:', ind+1)

[[4 6 2 2 8 8 3 8 7 8]
 [0 0 7 0 5 5 6 8 3 2]
 [2 7 4 2 4 9 0 9 7 8]
 [8 7 7 6 8 4 5 1 0 3]
 [5 7 6 9 8 4 3 9 3 6]
 [7 8 9 9 5 7 9 6 2 2]
 [5 5 9 9 9 0 0 8 9 5]
 [7 2 5 4 7 4 0 8 4 0]]
строка: [0 0 7 0 5 5 6 8 3 2]
сумма: 36 индекс строки: 2


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import math

arr2 = np.arange(127, 132).reshape(5, 1)
arr3 = np.arange(20, 25).reshape(5, 1)

evrast = math.dist(arr2, arr3)
print(evrast)

239.25927359247748


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
minus_c = c * (-1)

a_inverse = np.linalg.inv(a)
b_inverse = np.linalg.inv(b)
x = np.dot(a_inverse, minus_c)
x = np.dot(x, b_inverse)

print(x)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('minutes_n_ingredients.csv', skiprows=1, header=None)

numpy_array = np.array(data)

print(numpy_array[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [ ]:
fille = (np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1))
print(fille [:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('1 столбец:\n')
print(np.mean(fille[:, 1]))
print(np.min(fille[:, 1]))
print(np.max(fille[:, 1]))
print(np.median(fille[:, 1]))
print('\n2 столбец:\n')
print(np.mean(fille[:, 2]))
print(np.min(fille[:, 2]))
print(np.max(fille[:, 2]))
print(np.median(fille[:, 2]))

1 столбец:

21601.00169
0
2147483647
40.0

2 столбец:

9.05528
1
39
9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
print(np.quantile(fille[:, 1], .75))

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
ze_rose = np.count_nonzero(fille[:, 1] == 0)
fille[:, 1] = np.where(fille[:, 1] == 0, 1, fille[:, 1])
#print()
print(ze_rose)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
len(np.unique(fille[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(len(set(fille[:, 2])))

37


In [ ]:
d6, count = np.unique(fille[:, 2], return_counts=True)
for i, j in zip(d6, count):
  print(f'Кол-во ингридиентов {i} встретилось {j} раз')

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
only_five = fille[np.where(fille[:, 2]<=5)]
only_five

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

In [ ]:
only_five_2 = fille[fille[:, 2]<=5]
only_five_2

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
average_ingredients = fille[:, 2]/fille[:, 1]
print(average_ingredients)
print(max(average_ingredients))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
sorted_data = fille[fille[:, 1].argsort()[::-1]]
top = sorted_data[:100]
avg_ingredients = np.average(top[:, 2])
print('Ср кол-во ингредиентов для топ-100 рецептов:', avg_ingredients)

Ср кол-во ингредиентов для топ-100 рецептов: 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
total_recipes = fille.shape[0]
random_indices=np.random.choice(total_recipes, size=10, replace=False)
random_recipes=fille[random_indices]
print('Инфо-я о рандомно выбранных 10 рецетах:')
print(random_recipes)

Инфо-я о рандомно выбранных 10 рецетах:
[[443789     10     15]
 [157540    248      3]
 [163800    375      8]
 [457902     90      8]
 [107564     29     11]
 [ 35771    110     14]
 [311927     10      6]
 [ 62383     55      9]
 [237675     45      3]
 [ 70748    360     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
!!!len(np.where(fille[:, 2]<fille[:, 2]. mean()))/fille.shape[0]*100

["/bin/bash: -c: line 1: syntax error near unexpected token `np.where'",
 "/bin/bash: -c: line 1: `!len(np.where(fille[:, 2]<fille[:, 2]. mean()))/fille.shape[0]*100'"]

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
gr = np.zeros((fille.shape[0], 4), dtype=int)

13. Выведите процент "простых" рецептов в датасете

In [ ]:
str(sum(good_recepts[:, 3])/data.shape[0]*100)+'%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.